name: Sync to Production Repositories

on:
  push:
    branches:
      - ie20935
  # Permite la ejecución manual para pruebas
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ie20935

      - name: Configure Git
        run: |
          git config --global user.name "SIASIS IE20935 Sync Bot"
          git config --global user.email "siasis-sync@asuncion8.edu.pe"

      - name: Push to Repository 1
        run: |
          echo "Configurando repositorio de destino..."
          git remote add repo1 https://x-access-token:${{ secrets.SIU01_INS1_REPOSITORIO_PRODUCCION_TOKEN }}@github.com/SIU01-ASUNCION8-SIASIS/SIU01-INS1-IE20935.git

          echo "Clonando repositorio destino a un directorio temporal..."
          mkdir -p temp-repo
          cd temp-repo
          git clone https://x-access-token:${{ secrets.SIU01_INS1_REPOSITORIO_PRODUCCION_TOKEN }}@github.com/SIU01-ASUNCION8-SIASIS/SIU01-INS1-IE20935.git .

          echo "Copiando contenido actual sobre el repositorio destino..."
          find .. -mindepth 1 -maxdepth 1 -not -path "../.git" -not -path "../temp-repo" -exec cp -r {} . \;

          echo "Verificando cambios..."
          git status

          echo "Añadiendo todos los cambios..."
          git add -A

          echo "Creando commit con los cambios..."
          git commit -m "Sync changes from ie20935 branch"

          echo "Haciendo push de los cambios al repositorio destino..."
          git push origin master
